### ISSUE TITLE
Can not set timebase and samples/s to meaningful values for DSO-2090

### ISSUE THREAD

**Issue by tmshlvck** [OpenHantek/openhantek#130]
It seems that with DSO-2090 the only Record Length value that produces any output is Roll. And with that I can't set any meaningful samples/s and timebase values to see any low frequency signal, say 2kHz squares from the reference in the scope.

Attempts to change the Record Length value when the scope is running ends up with crash & segmentation failure with the following stack trace:

```
Thread 1 "OpenHantek" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff4f53f5d in __GI_abort () at abort.c:90
#2  0x00007ffff58fa095 in __gnu_cxx::__verbose_terminate_handler() ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff58f7c86 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff58f7cd1 in std::terminate() ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff58f7f14 in __cxa_throw ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x0000555555577406 in HorizontalDock::setRecordLength (this=this@entry=
    0x55555586db30, recordLength=<optimized out>)
    at /home/brill/openhantek-2017-12/openhantek/src/docks/HorizontalDock.cpp:140
#7  0x0000555555577662 in HorizontalDock::availableRecordLengthsChanged (
    this=0x55555586db30, recordLengths=...)
    at /home/brill/openhantek-2017-12/openhantek/src/docks/HorizontalDock.cpp:167
#8  0x00007ffff5ea69ff in QMetaObject::activate(QObject*, int, int, void**) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#9  0x00005555555abe65 in HantekDsoControl::availableRecordLengthsChanged (
    this=this@entry=0x7fffffffdc70, _t1=...)
    at /home/brill/openhantek-2017-12/build/openhantek/OpenHantek_autogen/QCBJVIA7PY/moc_hantekdsocontrol.cpp:424
#10 0x0000555555590edb in HantekDsoControl::updateSamplerate (
    this=this@entry=0x7fffffffdc70, downsampler=24, 
    fastRate=fastRate@entry=false)
    at /home/brill/openhantek-2017-12/openhantek/src/hantek/hantekdsocontrol.cpp:809
#11 0x00005555555913e1 in HantekDsoControl::setSamplerate (
    this=0x7fffffffdc70, samplerate=<optimized out>)
    at /home/brill/openhantek-2017-12/openhantek/src/hantek/hantekdsocontrol.cpp:879
#12 0x000055555559161d in HantekDsoControl::restoreTargets (
    this=this@entry=0x7fffffffdc70)
    at /home/brill/openhantek-2017-12/openhantek/src/hantek/hantekdsocontrol.cpp:822
#13 0x0000555555591722 in HantekDsoControl::updateRecordLength (
    this=0x7fffffffdc70, index=1)
    at /home/brill/openhantek-2017-12/openhantek/src/hantek/hantekdsocontrol.cpp:693
---Type <return> to continue, or q <return> to quit---
#14 0x00005555555917a2 in HantekDsoControl::setRecordLength (
    this=0x7fffffffdc70, index=1)
    at /home/brill/openhantek-2017-12/openhantek/src/hantek/hantekdsocontrol.cpp:844
#15 0x00007ffff5ea69ff in QMetaObject::activate(QObject*, int, int, void**) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#16 0x00005555555ab782 in HorizontalDock::recordLengthChanged (
    this=this@entry=0x55555586db30, _t1=<optimized out>, _t1@entry=1)
    at /home/brill/openhantek-2017-12/build/openhantek/OpenHantek_autogen/KNODL3TGKI/moc_HorizontalDock.cpp:272
#17 0x00005555555778f1 in HorizontalDock::recordLengthSelected (
    this=0x55555586db30, index=1)
    at /home/brill/openhantek-2017-12/openhantek/src/docks/HorizontalDock.cpp:215
#18 0x00005555555ad8fb in HorizontalDock::qt_static_metacall (
    _o=0x55555586db30, _c=<optimized out>, _id=<optimized out>, 
    _a=<optimized out>)
    at /home/brill/openhantek-2017-12/build/openhantek/OpenHantek_autogen/KNODL3TGKI/moc_HorizontalDock.cpp:148
#19 0x00007ffff5ea68e5 in QMetaObject::activate(QObject*, int, int, void**) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#20 0x00007ffff6ce3fa1 in QComboBox::currentIndexChanged(int) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#21 0x00007ffff6ce5fc3 in ?? ()
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#22 0x00007ffff6ce74ac in ?? ()
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#23 0x00007ffff6ce7641 in ?? ()
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#24 0x00007ffff6cecf9d in ?? ()
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#25 0x00007ffff5ea68e5 in QMetaObject::activate(QObject*, int, int, void**) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#26 0x00007ffff6ce4639 in ?? ()
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#27 0x00007ffff5e77acc in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#28 0x00007ffff6bf2445 in QApplicationPrivate::notify_helper(QObject*, QEvent*)
    () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#29 0x00007ffff6bfa28f in QApplication::notify(QObject*, QEvent*) ()
---Type <return> to continue, or q <return> to quit---
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#30 0x00007ffff5e77de8 in QCoreApplication::notifyInternal2(QObject*, QEvent*)
    () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#31 0x00007ffff6bf9262 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#32 0x00007ffff6c4d685 in ?? ()
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#33 0x00007ffff6c4ffba in ?? ()
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#34 0x00007ffff6bf246c in QApplicationPrivate::notify_helper(QObject*, QEvent*)
    () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#35 0x00007ffff6bf9d34 in QApplication::notify(QObject*, QEvent*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#36 0x00007ffff5e77de8 in QCoreApplication::notifyInternal2(QObject*, QEvent*)
    () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#37 0x00007ffff6436f43 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#38 0x00007ffff6438a25 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#39 0x00007ffff6410cab in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#40 0x00007fffeda555a0 in ?? ()
   from /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#41 0x00007ffff12e5fb7 in g_main_context_dispatch ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#42 0x00007ffff12e61f0 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#43 0x00007ffff12e627c in g_main_context_iteration ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#44 0x00007ffff5ed047f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#45 0x00007ffff5e75e3a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#46 0x00007ffff5e7eda4 in QCoreApplication::exec() ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#47 0x000055555556dc8c in main (argc=<optimized out>, argv=<optimized out>)
    at /home/brill/openhantek-2017-12/openhantek/src/main.cpp:177

```

**Comment by davidgraeff** [comment]
Would you please try again? This might be fixed now.

**Comment by davidgraeff** [comment]
Please reopen if it still doesn't work for you :)
