### ISSUE TITLE
Thread 7 "dataAnalyzerThr" received signal SIGABRT, Aborted.

### ISSUE THREAD

**Issue by phmarek** [OpenHantek/openhantek#133]
Using 997a01ec72e12d346296981268020be654fbb5b6 or later commits I get

```
terminate called after throwing an instance of 'std::runtime_error*'

Thread 7 "dataAnalyzerThr" received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffcaf3a700 (LWP 3048)]
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51      ../sysdeps/unix/sysv/linux/raise.c: Datei oder Verzeichnis nicht gefunden.
(gdb) bt
#0  0x00007ffff492fa70 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff493119a in __GI_abort () at abort.c:89
#2  0x00007ffff525ab85 in __gnu_cxx::__verbose_terminate_handler() () at /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff5258956 in  () at /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff52589a1 in  () at /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff5258be4 in  () at /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00005555555831d2 in GlGenerator::generateGraphs(DataAnalyzerResult const*) (this=0x555555d56e70, result=0x7fffc40017d0) at openhantek/src/glgenerator.cpp:240
#7  0x000055555557a8d9 in DsoWidget::doShowNewData() (this=this@entry=0x555555d56b70) at openhantek/src/dsowidget.cpp:448
#8  0x000055555557aca7 in DsoWidget::showNewData(std::unique_ptr<DataAnalyzerResult, std::default_delete<DataAnalyzerResult> >) (this=this@entry=0x555555d56b70, data=std::unique_ptr<DataAnalyzerResult> containing 0x0) at openhantek/src/dsowidget.cpp:232
#9  0x0000555555591a05 in OpenHantekMainWindow::<lambda()>::operator() (__closure=<optimized out>) at openhantek/src/mainwindow.cpp:55
#10 0x0000555555591a05 in QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, OpenHantekMainWindow::OpenHantekMainWindow(HantekDsoControl*, DataAnalyzer*, DsoSettings*)::<lambda()> >::call (arg=<optimized out>, f=...) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:130
#11 0x0000555555591a05 in QtPrivate::Functor<OpenHantekMainWindow::OpenHantekMainWindow(HantekDsoControl*, DataAnalyzer*, DsoSettings*)::<lambda()>, 0>::call<QtPrivate::List<>, void> (arg=<optimized out>, f=...) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:240
#12 0x0000555555591a05 in QtPrivate::QFunctorSlotObject<OpenHantekMainWindow::OpenHantekMainWindow(HantekDsoControl*, DataAnalyzer*, DsoSettings*)::<lambda()>, 0, QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase *, QObject *, void **, bool *) (which=<optimized out>, this_=<optimized out>, r=<optimized out>, a=<optimized out>, ret=<optimized out>)
    at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobject_impl.h:168
#13 0x00007ffff5800e6f in QMetaObject::activate(QObject*, int, int, void**) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#14 0x000055555556eb6e in DataAnalyzer::samplesAvailable() (this=0x7fffffffd9c0) at openhantek/src/analyse/dataanalyzer.cpp:119
#15 0x00007ffff58018c2 in QObject::event(QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#16 0x00007ffff64ed59c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#17 0x00007ffff64f4e64 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#18 0x00007ffff57d2258 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#19 0x00007ffff57d49cd in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#20 0x00007ffff582bac3 in  () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#21 0x00007ffff29a6fa7 in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#22 0x00007ffff29a71e0 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#23 0x00007ffff29a726c in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#24 0x00007ffff582b0ef in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#25 0x00007ffff57d02aa in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#26 0x00007ffff55ef35a in QThread::exec() () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#27 0x00007ffff55f422d in  () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#28 0x00007ffff6fe9519 in start_thread (arg=0x7fffcaf3a700) at pthread_create.c:456
#29 0x00007ffff49e8a4f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97
```

db4f8ba0b7b2bcc9ee7f41c96b597cdda56acacc is okay.

**Comment by davidgraeff** [comment]
I think this is fixed now, please reopen if this still does not work for you.
