### ISSUE TITLE
Crashes immediately when hitting x-y mode button

### ISSUE THREAD

**Issue by wom-bat** [OpenHantek/openhantek#170]
Using a DS6022BE, and the tip of the git tree 16dc684e03fa0c1003d9eeaa826b8d9198ff731d￼ 
Hitting switching mode from T-Y to X-Y causes a segmentation fault.

I'm running on Debian `sid'.  
Backtrace is:

```
Thread 1 "OpenHantek" received signal SIGSEGV, Segmentation fault.
0x0000555555585b93 in Graph::writeData (this=0x7fffe4008910, 
    data=0x7fffc0004040, program=0x555555f944d0, vertexLocation=0)
    at /home/peterc/src/openhantek/openhantek/src/glscopegraph.cpp:56
56              buffer.write(offset, gSpectrum.data(), dataSize);

(gdb) bt
#0  0x0000555555585b93 in Graph::writeData(PPresult*, QOpenGLShaderProgram*, int) (this=0x7fffe4008910, data=0x7fffc0004040, program=0x555555f944d0, vertexLocation=0) at /home/peterc/src/openhantek/openhantek/src/glscopegraph.cpp:56
#1  0x0000555555583d71 in GlScope::showData(PPresult*) (this=0x555555d9a960, data=0x7fffc0004040) at /home/peterc/src/openhantek/openhantek/src/glscope.cpp:236
#2  0x000055555557cd87 in DsoWidget::showNew(std::shared_ptr<PPresult>) (this=0x55555590aa30, data=std::shared_ptr (count 3, weak 0) 0x7fffc0004040)
    at /home/peterc/src/openhantek/openhantek/src/dsowidget.cpp:494
#3  0x00005555555955f5 in MainWindow::showNewData(std::shared_ptr<PPresult>) (this=<optimized out>, data=...)
    at /home/peterc/src/openhantek/openhantek/src/mainwindow.cpp:281
#4  0x0000555555593723 in QtPrivate::FunctorCall<QtPrivate::IndexesList<0>, QtPrivate::List<std::shared_ptr<PPresult> >, void, void (MainWindow::*)(std::shared_ptr<PPresult>)>::call(void (MainWindow::*)(std::shared_ptr<PPresult>), MainWindow*, void**) (arg=<optimized out>, o=<optimized out>, f=<optimized out>)
    at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:136
#5  0x0000555555593723 in QtPrivate::FunctionPointer<void (MainWindow::*)(std::shared_ptr<PPresult>)>::call<QtPrivate::List<std::shared_ptr<PPresult> >, void>(void (MainWindow::*)(std::shared_ptr<PPresult>), MainWindow*, void**) (arg=<optimized out>, o=<optimized out>, f=<optimized out>)
    at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:169
#6  0x0000555555593723 in QtPrivate::QSlotObject<void (MainWindow::*)(std::shared_ptr<PPresult>), QtPrivate::List<std::shared_ptr<PPresult> >, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) (which=<optimized out>, this_=<optimized out>, r=<optimized out>, a=<optimized out>, ret=<optimized out>)
    at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobject_impl.h:120
#7  0x00007ffff57ff8c2 in QObject::event(QEvent*) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#8  0x00007ffff652a2a3 in QWidget::event(QEvent*) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#9  0x00007ffff663ceeb in QMainWindow::event(QEvent*) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#10 0x00007ffff64eb59c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#11 0x00007ffff64f2e64 in QApplication::notify(QObject*, QEvent*) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#12 0x00007ffff57d0258 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#13 0x00007ffff57d29cd in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#14 0x00007ffff5829ac3 in  () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#15 0x00007ffff2959fb7 in g_main_context_dispatch ()
    at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#16 0x00007ffff295a1f0 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#17 0x00007ffff295a27c in g_main_context_iteration ()
    at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#18 0x00007ffff58290ef in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#19 0x00007ffff57ce2aa in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#20 0x00007ffff57d7214 in QCoreApplication::exec() ()
    at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#21 0x000055555556fe34 in main(int, char**) (argc=<optimized out>, argv=<optimized out>) at /home/peterc/src/openhantek/openhantek/src/main.cpp:159
```
`

**Comment by dendvz** [comment]
RC is attempt to address an element by reference beyond upper bound of a vector.
